const RenteManagement = (() => {
  const initGrid = () => {
    let data = [
      {
        roomNumber: '101',
        fullName: 'Nguyễn Văn A',
        socialId: '123456789',
        phoneNumber: '0909999000',
        permanentAddress: '11/12B Khu Máy Nước Nha Trang Khánh Hòa',
        tempResidenceStatus: '1',
        relationship: 'Chồng',
        contractType: 'Dài hạn',
        contractDate: '24/11/2022',
        stayingStartDate: '30/11/2022',
        stayingEndDate: '',
      },
      {
        roomNumber: '101',
        fullName: 'Nguyễn Văn A',
        socialId: '123456789',
        phoneNumber: '0909999000',
        permanentAddress: '11/12B Khu Máy Nước Nha Trang Khánh Hòa',
        tempResidenceStatus: '0',
        relationship: 'Chồng',
        contractType: 'Dài hạn',
        contractDate: '24/11/2022',
        stayingStartDate: '30/11/2022',
        stayingEndDate: '',
      },
      {
        roomNumber: '101',
        fullName: 'Nguyễn Văn A',
        socialId: '123456789',
        phoneNumber: '0909999000',
        permanentAddress: '11/12B Khu Máy Nước Nha Trang Khánh Hòa',
        tempResidenceStatus: '0',
        relationship: 'Chồng',
        contractType: 'Dài hạn',
        contractDate: '24/11/2022',
        stayingStartDate: '30/11/2022',
        stayingEndDate: '',
      },
      {
        roomNumber: '101',
        fullName: 'Nguyễn Văn A',
        socialId: '123456789',
        phoneNumber: '0909999000',
        permanentAddress: '11/12B Khu Máy Nước Nha Trang Khánh Hòa',
        tempResidenceStatus: '1',
        relationship: 'Chồng',
        contractType: 'Dài hạn',
        contractDate: '24/11/2022',
        stayingStartDate: '30/11/2022',
        stayingEndDate: '',
      },
      {
        roomNumber: '101',
        fullName: 'Nguyễn Văn A',
        socialId: '123456789',
        phoneNumber: '0909999000',
        permanentAddress: '11/12B Khu Máy Nước Nha Trang Khánh Hòa',
        tempResidenceStatus: '1',
        relationship: 'Chồng',
        contractType: 'Dài hạn',
        contractDate: '24/11/2022',
        stayingStartDate: '30/11/2022',
        stayingEndDate: '',
      },
      {
        roomNumber: '101',
        fullName: 'Nguyễn Văn A',
        socialId: '123456789',
        phoneNumber: '0909999000',
        permanentAddress: '11/12B Khu Máy Nước Nha Trang Khánh Hòa',
        tempResidenceStatus: '1',
        relationship: 'Chồng',
        contractType: 'Dài hạn',
        contractDate: '24/11/2022',
        stayingStartDate: '30/11/2022',
        stayingEndDate: '',
      },
    ];

    let grid = {
      view: 'datatable',
      scrollY: true,
      data: data,
      height: 200,
      minHeight: 400,
      select: 'row',
      editable: false,
      css: 'webix_header_border webix_data_border highlight',
      columns: [
        { id: 'roomNumber', header: 'Phòng', minWidth: 100 },
        { id: 'fullName', header: 'Tên', width: 300 },
        { id: 'socialId', header: 'CMND', width: 120 },
        { id: 'phoneNumber', header: 'Số điện thoại', width: 120 },
        { id: 'permanentAddress', header: 'Đ/c thường trú', width: 500 },
        {
          id: 'tempResidenceStatus',
          header: 'ĐK Tạm trú',
          width: 50,
          template: '{common.checkbox()}',
          checkValue: '1',
          readonly: true,
          //   uncheckValue: 'off',
        },
        { id: 'relationship', header: 'QH người thuê', width: 130 },
        { id: 'contractType', header: 'Loại HĐ', width: 120 },
        { id: 'contractDate', header: 'Ngày kí HĐ', width: 120 },
        { id: 'stayingStartDate', header: 'Ngày bắt đầu', width: 120 },
        { id: 'stayingEndDate', header: 'Ngày kết thúc', width: 120 },
      ],
    };
    return grid;
    // webix.ui(grid);
  };
  return {
    initGrid,
  };
})();
